### PR TITLE
Webpack 5

### PR DESCRIPTION
**Pull request by gcauchon**
## 📖 Description

Many NPM dependencies are dropping support for Webpack `4`, this PR convert the asset pipeline to Webpack `5`.

Before | After
--- | ---
Screen Shot 2021-05-31 at 9 11 14 PM | Screen Shot 2021-06-22 at 2 33 49 PM

## 📝 Notes

There was an effort on the Phoenix and Phoenix.LiveView repositories to rewrite the assets pipeline! My feeling is it the first step toward converting to TS…

- Issue/proposition [here](https://github.com/phoenixframework/phoenix/issues/4328)
- PR [here](https://github.com/phoenixframework/phoenix/pull/4337)

## 📓 References

Based on #150. I will `rebase` once it merges upstream…

## 🦀 Dispatch

- `#dispatch/elixir`

### CODE REVIEW

**Comment by bcardarella** [comment]
@gcauchon my PR #4337 updates to Webpack v5 already along with the other changes to the asset pipeline. As far as Typescript goes, my preference would be to move to TS as I suspect some edge case errors can be surfaced. However, as I understand it the reality of supporting TS for Phoenix may be a complex issue. Most of the existing Phoenix JS has been built by a small number of contributors. Migrating to TS could result in even less people that can contribute and maintain.

**Comment by gcauchon** [comment]
> ~@gcauchon my PR #4337 updates to Webpack v5 already along with the other changes to the asset pipeline. As far as Typescript goes, my preference would be to move to TS as I suspect some edge case errors can be surfaced. However, as I understand it the reality of supporting TS for Phoenix may be a complex issue. Most of the existing Phoenix JS has been built by a small number of contributors. Migrating to TS could result in even less people that can contribute and maintain.~
> 
> **Edit** nevermind, I didn't notice that this was on a different repo from Phoenix. Sorry!

@bcardarella I've been using Webpack 5 in my private repos for a few weeks already when I found out you were in the process of rewriting the pipeline to leverage a more up-to-date/in-depth approach. 

Your comment still makes 100% sense for anyone using either `mix phx.new` or forking this GitHub _template_ as it helps understand where the community is stearing toward!

**Review by Boubalou — APPROVED** [review]
Nicely done.

**Comment by gcauchon** [comment]
https://github.com/phoenixframework/phoenix/pull/4337 was merged today! I will completed the cleanup and remove `babel` now that it is not supported upstream anymore!

**Comment by gcauchon** [comment]
@remi @simonprev I just `rebase` #150 so the changes now only reflect the _Webpack 5_ work done!

**Pull request merged**
