### PR TITLE
Add `actions-permissions/monitor` action in CI workflow

### PR DESCRIPTION
**Pull request by remi**
## 📖 Description

GitHub [recently introduced](https://github.blog/2023-06-26-new-tool-to-secure-your-github-actions) a few actions to monitor action permissions usage.

Let’s use the [monitor action](https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor) to track needed permissions.

## 🦀 Dispatch

- `#dispatch/devops`

### CODE REVIEW

**Comment by Boubalou** [comment]
No more changes! WOAAAAA

**Comment by remi** [comment]
👀 https://github.com/GitHubSecurityLab/actions-permissions/issues/4

**Comment by remi** [comment]
I might reopen it if https://github.com/GitHubSecurityLab/actions-permissions/pull/5 works 😎

**Comment by remi** [comment]
It’s Docker’s turn now! 😰 

https://github.com/GitHubSecurityLab/actions-permissions/pull/5#issuecomment-1611642832

**Pull request closed without merging**
