### PR TITLE
Use versions from .tool-versions for CI

### LINKED ISSUE #34: Add Absinthe GraphQL tooling
We have been using [GraphQL](https://graphql.org/) on every web projects for months, I think we should include the [Absinthe](https://absinthe-graphql.org/) setup in the _boilerplate_ to simplify scaffolding of upcoming Elixir projects.

### PR DESCRIPTION
**Pull request by JoeyBG**
## 📖 Description

Instead of manually having to update the CI workflow file, we can leverage recently merged functionality (https://github.com/actions/setup-node/pull/373 & https://github.com/erlef/setup-beam/pull/159) to automatize this.

## 🦀 Dispatch

- `#dispatch/devops`

### CODE REVIEW

**Review by simonprev — APPROVED** [review]
Awesome!

**Review by Boubalou — COMMENTED** [review]
TIL!

**Comment by remi** [comment]
Une belle idée de post "TIL" sur https://craft.mirego.com ça! 😁

**Review by gcauchon — COMMENTED** [review]
TIL!

**Pull request merged**
