### PR TITLE
Update mix.lock to be compatible with hex v0.20.2+

### PR DESCRIPTION
**Pull request by remi**
Yesterday’s [`hex 0.20.2` release](https://github.com/hexpm/hex/releases/tag/v0.20.2) requires us to regenerate `mix.lock` checksums.

### CODE REVIEW

**Comment by gcauchon** [comment]
@ericmj has an interesting comment on the forum thread I started on the forum!

https://elixirforum.com/t/docker-build-started-failling-today/28844/6

> This happens when you have a manifest file that is newer than your mix.lock file. That’s because you run mix deps.get which updates your manifest and lock file but then your dockefile’s COPY command introduces the old lockfile again. I would recommend against doing COPY . . in your dockerfile, you should instead only copy what is needed for the next build step.
>
> I will publish a new release of Hex that mitigates this issue.

I will explore on this avenue tonight!

**Comment by remi** [comment]
Alright, I’ll close this PR since it only provides a short-term solution to the current situation — it doesn’t protect against future breaking changes that might occur with `hex`.

**Comment by ericmj** [comment]
Sorry for interjecting (I was mentioned above). It is still a good idea to update the lockfile to the new format since it is more secure and most `mix deps.*` tasks will try to update to it anyway.

**Comment by remi** [comment]
@ericmj Yes, I spoke with @gcauchon and his next pull request (based on your `COPY . .` comment) will do that as well 😄

**Comment by gcauchon** [comment]
^this 🍻

**Pull request closed without merging**
